### ISSUE TITLE
plone-logged-in contains tinymce styles

### ISSUE THREAD

**Issue by pnicolli** [plone/Products.CMFPlone#2430]
### What I did:
Install a fresh Plone 5.1.2 site. Add my own add-on.

In the add-on, add a bundle that contains css.
```xml
<records prefix="plone.bundles/my-css-bundle"
           interface='Products.CMFPlone.interfaces.IBundleRegistry'>
    <value key="enabled">True</value>
    <value key="compile">True</value>
    <value key="depends">plone</value>
    <!-- other configs -->
</records>
```

The CSS files include these lines, for example:
```css
body {
    font-family: 'Titillium Web', 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-size: 17px;
    line-height: 1.5;
    color: #1c2024;
    background-color: #fff;
}
```

### What I expect to happen:
I expected the site font to be set by my styles

### What actually happened:
The body font is set by [a css file](https://github.com/plone/Products.CMFPlone/blob/5.1.2/Products/CMFPlone/static/components/tinymce-builded/js/tinymce/skins/lightgray/content.min.css) that was previously only added in the tinymce frames. From a quick check of the repo history, it appears that since Plone 5.1.1 this file is cooked into the plone-logged-in bundle by default.
I have a Plone 5.1rc2 site in production and it's not included there, upgrading to Plone 5.1.1 or Plone 5.1.2.1 would break the site styles with this change.

### What version of Plone/ Addons I am using:
Products.CMFPlone 5.1.2.1
