### ISSUE TITLE
citation not formatted anyhow (blockquote)

### ISSUE THREAD

**Issue by ksuess** [plone/Products.CMFPlone#4063]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote
`The <blockquote> [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element indicates that the enclosed text is an extended quotation.`

go to https://classic.demo.plone.org/en

- create page
- mark text as blockquote
- sve page
- see that marked text passage looks like normal paragraph and is not formatted, not indented, not marked with quotation markes, nothing.

I expect blockquote nodes to be formatted somehow. It's opinionatied, but should not be ignored completely IMHO.

**Comment by ksuess** [comment]
[EDIT]  there may be opinions on how to format a citation/blockquote, but it should not be ignored completely IMHO.

**Comment by stevepiercy** [comment]
I'd suggest pulling the style from Bootstrap for blockquote: https://getbootstrap.com/docs/5.3/content/typography/#blockquotes.

@ksuess thanks for reporting. If you don't have time to work on it, perhaps someone from the @plone/classicui-team can add information here about which package needs to be updated and how, to help this issue move forward.

**Comment by yurj** [comment]
something like
```
blockquote {
    @extend .blockquote;
}
``` 
?

**Comment by petschki** [comment]
hm ... `.blockquote` only raises the font-size to `1.25rem` and does a margin-bottom ... thats not really obvious as a blocked quote to me. We could implement something more barcelonetish here like this:


```scss
blockquote {
    @extend .blockquote;  // font-size and margin
    background: var(--bs-light-bg-subtle);
    border-left: var(--bs-border-style) 5px var(--bs-border-color);
    color: var(--bs-light-text-emphasis);
    padding: $spacer;
}
```

leads to something like this:

<img width="949" alt="Bildschirmfoto 2024-11-21 um 07 19 16" src="https://github.com/user-attachments/assets/5d818643-c98c-49fe-8b79-436a024ae7ba">


note that using the variables ensures the correct coloring for light and dark mode (see https://classic.demo.plone.org/@@test-rendering-cheatsheet)
