### ISSUE TITLE
@@manage-viewlets is defective

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#782]
The viewlet manager displays the wrong actions - "show" is displayed for already shown viewlets and therefore not possible to hide viewlets.

Also adding some borders as in p4 would be useful to show the nested structure of the viewlets.

**Comment by pbauer** [comment]
Functionality:
The js fires two ajax-request resulting in no change at all. I only see it registered one. Why is this happening?
Here is the js:
```js
(function($) {
    $(function() {
        $('.managedViewlets').on('click', '.up, .down, .hide, .show', function (e) {
              e.preventDefault();
              var url = $(e.currentTarget).attr('href'),
                  vm = $(e.delegateTarget);
              $(vm).load(url + ' #' + $(vm).attr('id') + '.managedViewlets > dl');
        });
    });
})(jQuery);
```
Style:
In ``plone/app/viewletmanager/manage-viewlets.pt`` the css added to templates using `with fill-slot="style_slot"` does not work anymore in Plone 5. Do we need to register a new resource for that or put it inline? 

Also in ``plone/app/viewletmanager/manage-viewletmanager.pt`` the ``visualClear`` has to be replaced by ``clearfix``

There is the css:
```css
.viewletmanager, .viewlet { display: block; margin: .5em;}
.viewletmanager { border: 1px solid #000;}
.viewletmanager > dt { border-bottom: 1px solid #000; }
.viewletmanager > dt, .viewlet > dt { font-size: .8em; background: #EEE; padding: .5em; }
.viewlet { border: 1px solid #999; }
.viewlet > dt { border-bottom: 1px solid #999; }
.viewlet > dt > a.show { display: none !important; }
.viewlet > dt > a.hide { display: inline !important; }
.viewletmanager dd, .viewlet dd { padding: .5em; }
.viewlet.hiddenViewlet > dt > a.hide { display:none !important; }
.viewlet.hiddenViewlet > dt > a.show { display: inline !important; }
```
